// Generated by gencpp from file project_isds/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PROJECT_ISDS_MESSAGE_ADDTWOINTS_H
#define PROJECT_ISDS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <project_isds/AddTwoIntsRequest.h>
#include <project_isds/AddTwoIntsResponse.h>


namespace project_isds
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace project_isds


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::project_isds::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::project_isds::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::project_isds::AddTwoInts > {
  static const char* value()
  {
    return "project_isds/AddTwoInts";
  }

  static const char* value(const ::project_isds::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::project_isds::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::project_isds::AddTwoInts >
template<>
struct MD5Sum< ::project_isds::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::project_isds::AddTwoInts >::value();
  }
  static const char* value(const ::project_isds::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::project_isds::AddTwoIntsRequest> should match
// service_traits::DataType< ::project_isds::AddTwoInts >
template<>
struct DataType< ::project_isds::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::project_isds::AddTwoInts >::value();
  }
  static const char* value(const ::project_isds::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::project_isds::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::project_isds::AddTwoInts >
template<>
struct MD5Sum< ::project_isds::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::project_isds::AddTwoInts >::value();
  }
  static const char* value(const ::project_isds::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::project_isds::AddTwoIntsResponse> should match
// service_traits::DataType< ::project_isds::AddTwoInts >
template<>
struct DataType< ::project_isds::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::project_isds::AddTwoInts >::value();
  }
  static const char* value(const ::project_isds::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECT_ISDS_MESSAGE_ADDTWOINTS_H
