// Generated by gencpp from file project_ISDS/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PROJECT_ISDS_MESSAGE_ADDTWOINTS_H
#define PROJECT_ISDS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <project_ISDS/AddTwoIntsRequest.h>
#include <project_ISDS/AddTwoIntsResponse.h>


namespace project_ISDS
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace project_ISDS


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::project_ISDS::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::project_ISDS::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::project_ISDS::AddTwoInts > {
  static const char* value()
  {
    return "project_ISDS/AddTwoInts";
  }

  static const char* value(const ::project_ISDS::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::project_ISDS::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::project_ISDS::AddTwoInts >
template<>
struct MD5Sum< ::project_ISDS::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::project_ISDS::AddTwoInts >::value();
  }
  static const char* value(const ::project_ISDS::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::project_ISDS::AddTwoIntsRequest> should match
// service_traits::DataType< ::project_ISDS::AddTwoInts >
template<>
struct DataType< ::project_ISDS::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::project_ISDS::AddTwoInts >::value();
  }
  static const char* value(const ::project_ISDS::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::project_ISDS::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::project_ISDS::AddTwoInts >
template<>
struct MD5Sum< ::project_ISDS::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::project_ISDS::AddTwoInts >::value();
  }
  static const char* value(const ::project_ISDS::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::project_ISDS::AddTwoIntsResponse> should match
// service_traits::DataType< ::project_ISDS::AddTwoInts >
template<>
struct DataType< ::project_ISDS::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::project_ISDS::AddTwoInts >::value();
  }
  static const char* value(const ::project_ISDS::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECT_ISDS_MESSAGE_ADDTWOINTS_H
